name: catdrive

on:
  repository_dispatch:
    types: catdrive
  push:
    tags:
      - CatDrive-**

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: Initialize environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update -y
        sudo -E apt-get install binfmt-support bsdtar build-essential debootstrap jq tar u-boot-tools wget xz-utils -y
        sudo -E apt-get clean

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Build CatDrive
      run: |
        make build_archlinux=y build_ubuntu=y build_debian=y build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: output/release/*

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        files: output/release/*
